package guide.bean;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_title
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String messageTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_crDay
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private Date messageCrday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.re_person_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String rePersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_id
     *
     * @return the value of message.message_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_id
     *
     * @param messageId the value for message.message_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_title
     *
     * @return the value of message.message_title
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getMessageTitle() {
        return messageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_title
     *
     * @param messageTitle the value for message.message_title
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle == null ? null : messageTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_crDay
     *
     * @return the value of message.message_crDay
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public Date getMessageCrday() {
        return messageCrday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_crDay
     *
     * @param messageCrday the value for message.message_crDay
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setMessageCrday(Date messageCrday) {
        this.messageCrday = messageCrday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.re_person_id
     *
     * @return the value of message.re_person_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getRePersonId() {
        return rePersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.re_person_id
     *
     * @param rePersonId the value for message.re_person_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setRePersonId(String rePersonId) {
        this.rePersonId = rePersonId == null ? null : rePersonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	@Override
	public String toString() {
		return "Message [messageId=" + messageId + ", messageTitle=" + messageTitle + ", messageCrday=" + messageCrday
				+ ", rePersonId=" + rePersonId + ", content=" + content + "]";
	}
}