package guide.bean;

public class QuestionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.stu_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String teacId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.stu_id
     *
     * @return the value of question.stu_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.stu_id
     *
     * @param stuId the value for question.stu_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.teac_id
     *
     * @return the value of question.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getTeacId() {
        return teacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.teac_id
     *
     * @param teacId the value for question.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setTeacId(String teacId) {
        this.teacId = teacId == null ? null : teacId.trim();
    }
}