package guide.bean;

import java.io.Serializable;

public class Student implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.tes_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String tesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String teacId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.class_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.mail
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.passwprd
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String passwprd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_id
     *
     * @return the value of student.stu_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_id
     *
     * @param stuId the value for student.stu_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.tes_id
     *
     * @return the value of student.tes_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getTesId() {
        return tesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.tes_id
     *
     * @param tesId the value for student.tes_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setTesId(String tesId) {
        this.tesId = tesId == null ? null : tesId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.teac_id
     *
     * @return the value of student.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getTeacId() {
        return teacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.teac_id
     *
     * @param teacId the value for student.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setTeacId(String teacId) {
        this.teacId = teacId == null ? null : teacId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.class_id
     *
     * @return the value of student.class_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.class_id
     *
     * @param classId the value for student.class_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_name
     *
     * @return the value of student.stu_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_name
     *
     * @param stuName the value for student.stu_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.phone
     *
     * @return the value of student.phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.phone
     *
     * @param phone the value for student.phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.mail
     *
     * @return the value of student.mail
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.mail
     *
     * @param mail the value for student.mail
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.passwprd
     *
     * @return the value of student.passwprd
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getPasswprd() {
        return passwprd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.passwprd
     *
     * @param passwprd the value for student.passwprd
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setPasswprd(String passwprd) {
        this.passwprd = passwprd == null ? null : passwprd.trim();
    }

	@Override
	public String toString() {
		return "Student [stuId=" + stuId + ", tesId=" + tesId + ", teacId=" + teacId + ", classId=" + classId
				+ ", stuName=" + stuName + ", phone=" + phone + ", mail=" + mail + ", passwprd=" + passwprd + "]";
	}
}