package guide.bean;
import java.lang.*;
public class depar {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depar.depar_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String depar_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depar.ins_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String ins_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depar.depar_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String depar_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depar.class_num
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private Integer class_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depar.depar_phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String depar_phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depar.depar_leadId
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String depar_leadId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depar.depar_id
     *
     * @return the value of depar.depar_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getDepar_id() {
        return depar_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depar.depar_id
     *
     * @param depar_id the value for depar.depar_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setDepar_id(String depar_id) {
        this.depar_id = depar_id == null ? null : depar_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depar.ins_id
     *
     * @return the value of depar.ins_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getIns_id() {
        return ins_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depar.ins_id
     *
     * @param ins_id the value for depar.ins_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setIns_id(String ins_id) {
        this.ins_id = ins_id == null ? null : ins_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depar.depar_name
     *
     * @return the value of depar.depar_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getDepar_name() {
        return depar_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depar.depar_name
     *
     * @param depar_name the value for depar.depar_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setDepar_name(String depar_name) {
        this.depar_name = depar_name == null ? null : depar_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depar.class_num
     *
     * @return the value of depar.class_num
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public Integer getClass_num() {
        return class_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depar.class_num
     *
     * @param class_num the value for depar.class_num
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setClass_num(Integer class_num) {
        this.class_num = class_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depar.depar_phone
     *
     * @return the value of depar.depar_phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getDepar_phone() {
        return depar_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depar.depar_phone
     *
     * @param depar_phone the value for depar.depar_phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setDepar_phone(String depar_phone) {
        this.depar_phone = depar_phone == null ? null : depar_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depar.depar_leadId
     *
     * @return the value of depar.depar_leadId
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getDepar_leadId() {
        return depar_leadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depar.depar_leadId
     *
     * @param depar_leadId the value for depar.depar_leadId
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setDepar_leadId(String depar_leadId) {
        this.depar_leadId = depar_leadId == null ? null : depar_leadId.trim();
    }
}