package guide.bean;

import java.util.Date;

public class File {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_id.file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_id.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String teacId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_id.file_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_id.file_path
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_id.file_date
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private Date fileDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_id.downloadTime
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private Integer downloadtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_id.file_id
     *
     * @return the value of file_id.file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_id.file_id
     *
     * @param fileId the value for file_id.file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_id.teac_id
     *
     * @return the value of file_id.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getTeacId() {
        return teacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_id.teac_id
     *
     * @param teacId the value for file_id.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setTeacId(String teacId) {
        this.teacId = teacId == null ? null : teacId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_id.file_name
     *
     * @return the value of file_id.file_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_id.file_name
     *
     * @param fileName the value for file_id.file_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_id.file_path
     *
     * @return the value of file_id.file_path
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_id.file_path
     *
     * @param filePath the value for file_id.file_path
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_id.file_date
     *
     * @return the value of file_id.file_date
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public Date getFileDate() {
        return fileDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_id.file_date
     *
     * @param fileDate the value for file_id.file_date
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setFileDate(Date fileDate) {
        this.fileDate = fileDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_id.downloadTime
     *
     * @return the value of file_id.downloadTime
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public Integer getDownloadtime() {
        return downloadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_id.downloadTime
     *
     * @param downloadtime the value for file_id.downloadTime
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setDownloadtime(Integer downloadtime) {
        this.downloadtime = downloadtime;
    }

	@Override
	public String toString() {
		return "File [fileId=" + fileId + ", teacId=" + teacId + ", fileName=" + fileName + ", filePath=" + filePath
				+ ", fileDate=" + fileDate + ", downloadtime=" + downloadtime + "]";
	}
}