package guide.bean;

public class Institute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institute.ins_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String insId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institute.ins_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String insName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institute.depar_num
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private Integer deparNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institute.ins_phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String insPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institute.ins_leaderId
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String insLeaderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institute.ins_id
     *
     * @return the value of institute.ins_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getInsId() {
        return insId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institute.ins_id
     *
     * @param insId the value for institute.ins_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setInsId(String insId) {
        this.insId = insId == null ? null : insId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institute.ins_name
     *
     * @return the value of institute.ins_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getInsName() {
        return insName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institute.ins_name
     *
     * @param insName the value for institute.ins_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setInsName(String insName) {
        this.insName = insName == null ? null : insName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institute.depar_num
     *
     * @return the value of institute.depar_num
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public Integer getDeparNum() {
        return deparNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institute.depar_num
     *
     * @param deparNum the value for institute.depar_num
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setDeparNum(Integer deparNum) {
        this.deparNum = deparNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institute.ins_phone
     *
     * @return the value of institute.ins_phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getInsPhone() {
        return insPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institute.ins_phone
     *
     * @param insPhone the value for institute.ins_phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setInsPhone(String insPhone) {
        this.insPhone = insPhone == null ? null : insPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institute.ins_leaderId
     *
     * @return the value of institute.ins_leaderId
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getInsLeaderid() {
        return insLeaderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institute.ins_leaderId
     *
     * @param insLeaderid the value for institute.ins_leaderId
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setInsLeaderid(String insLeaderid) {
        this.insLeaderid = insLeaderid == null ? null : insLeaderid.trim();
    }
}