package guide.bean;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mat_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String matId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mat_password
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String matPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mat_phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String matPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mat_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String matName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mat_id
     *
     * @return the value of manager.mat_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getMatId() {
        return matId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mat_id
     *
     * @param matId the value for manager.mat_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setMatId(String matId) {
        this.matId = matId == null ? null : matId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mat_password
     *
     * @return the value of manager.mat_password
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getMatPassword() {
        return matPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mat_password
     *
     * @param matPassword the value for manager.mat_password
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setMatPassword(String matPassword) {
        this.matPassword = matPassword == null ? null : matPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mat_phone
     *
     * @return the value of manager.mat_phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getMatPhone() {
        return matPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mat_phone
     *
     * @param matPhone the value for manager.mat_phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setMatPhone(String matPhone) {
        this.matPhone = matPhone == null ? null : matPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mat_name
     *
     * @return the value of manager.mat_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getMatName() {
        return matName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mat_name
     *
     * @param matName the value for manager.mat_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setMatName(String matName) {
        this.matName = matName == null ? null : matName.trim();
    }
}