package guide.bean;

public class Mmessage extends MmessageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 管理员消息表.rec_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String recId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 管理员消息表.rec_id
     *
     * @return the value of 管理员消息表.rec_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 管理员消息表.rec_id
     *
     * @param recId the value for 管理员消息表.rec_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setRecId(String recId) {
        this.recId = recId == null ? null : recId.trim();
    }
}