package guide.bean;

public class MmessageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 管理员消息表.message_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 管理员消息表.mat_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String matId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 管理员消息表.message_id
     *
     * @return the value of 管理员消息表.message_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 管理员消息表.message_id
     *
     * @param messageId the value for 管理员消息表.message_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 管理员消息表.mat_id
     *
     * @return the value of 管理员消息表.mat_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getMatId() {
        return matId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 管理员消息表.mat_id
     *
     * @param matId the value for 管理员消息表.mat_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setMatId(String matId) {
        this.matId = matId == null ? null : matId.trim();
    }
}