package guide.bean;

public class SdownfileKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdownfile.stu_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdownfile.file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String fileId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdownfile.stu_id
     *
     * @return the value of sdownfile.stu_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdownfile.stu_id
     *
     * @param stuId the value for sdownfile.stu_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdownfile.file_id
     *
     * @return the value of sdownfile.file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdownfile.file_id
     *
     * @param fileId the value for sdownfile.file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }
}