package guide.bean;

public class SmessageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 学生消息表.message_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column 学生消息表.stu_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String stuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 学生消息表.message_id
     *
     * @return the value of 学生消息表.message_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 学生消息表.message_id
     *
     * @param messageId the value for 学生消息表.message_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column 学生消息表.stu_id
     *
     * @return the value of 学生消息表.stu_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column 学生消息表.stu_id
     *
     * @param stuId the value for 学生消息表.stu_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }
}