package guide.bean;

import java.util.Date;

public class Tdownfile extends TdownfileKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdownfile.download_day
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private Date downloadDay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdownfile.download_day
     *
     * @return the value of tdownfile.download_day
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public Date getDownloadDay() {
        return downloadDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdownfile.download_day
     *
     * @param downloadDay the value for tdownfile.download_day
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setDownloadDay(Date downloadDay) {
        this.downloadDay = downloadDay;
    }
}