package guide.bean;

public class TdownfileKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdownfile.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String teacId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tdownfile.file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String fileId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdownfile.teac_id
     *
     * @return the value of tdownfile.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getTeacId() {
        return teacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdownfile.teac_id
     *
     * @param teacId the value for tdownfile.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setTeacId(String teacId) {
        this.teacId = teacId == null ? null : teacId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tdownfile.file_id
     *
     * @return the value of tdownfile.file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tdownfile.file_id
     *
     * @param fileId the value for tdownfile.file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }
}