package guide.bean;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String teacId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teac_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String teacName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teac_sex
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String teacSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teac_depar
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String teacDepar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.email
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.password
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teac_id
     *
     * @return the value of teacher.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getTeacId() {
        return teacId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teac_id
     *
     * @param teacId the value for teacher.teac_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setTeacId(String teacId) {
        this.teacId = teacId == null ? null : teacId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teac_name
     *
     * @return the value of teacher.teac_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getTeacName() {
        return teacName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teac_name
     *
     * @param teacName the value for teacher.teac_name
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setTeacName(String teacName) {
        this.teacName = teacName == null ? null : teacName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teac_sex
     *
     * @return the value of teacher.teac_sex
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getTeacSex() {
        return teacSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teac_sex
     *
     * @param teacSex the value for teacher.teac_sex
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setTeacSex(String teacSex) {
        this.teacSex = teacSex == null ? null : teacSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teac_depar
     *
     * @return the value of teacher.teac_depar
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getTeacDepar() {
        return teacDepar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teac_depar
     *
     * @param teacDepar the value for teacher.teac_depar
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setTeacDepar(String teacDepar) {
        this.teacDepar = teacDepar == null ? null : teacDepar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.email
     *
     * @return the value of teacher.email
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.email
     *
     * @param email the value for teacher.email
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.phone
     *
     * @return the value of teacher.phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.phone
     *
     * @param phone the value for teacher.phone
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.password
     *
     * @return the value of teacher.password
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.password
     *
     * @param password the value for teacher.password
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

	@Override
	public String toString() {
		return "Teacher [teacId=" + teacId + ", teacName=" + teacName + ", teacSex=" + teacSex + ", teacDepar="
				+ teacDepar + ", email=" + email + ", phone=" + phone + ", password=" + password + "]";
	}
    
}