package guide.dao;

import guide.bean.depar;

public interface deparMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depar
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int deleteByPrimaryKey(String depar_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depar
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insert(depar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depar
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insertSelective(depar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depar
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    depar selectByPrimaryKey(String depar_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depar
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKeySelective(depar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depar
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKey(depar record);
}