package guide.dao;

import guide.bean.Institute;

public interface InstituteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institute
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int deleteByPrimaryKey(String insId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institute
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insert(Institute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institute
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insertSelective(Institute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institute
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    Institute selectByPrimaryKey(String insId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institute
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKeySelective(Institute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institute
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKey(Institute record);
}