package guide.dao;

import guide.bean.Mmessage;
import guide.bean.MmessageKey;

public interface MmessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 管理员消息表
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int deleteByPrimaryKey(MmessageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 管理员消息表
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insert(Mmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 管理员消息表
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insertSelective(Mmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 管理员消息表
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    Mmessage selectByPrimaryKey(MmessageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 管理员消息表
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKeySelective(Mmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 管理员消息表
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKey(Mmessage record);
}