package guide.dao;

import guide.bean.Sdownfile;
import guide.bean.SdownfileKey;

public interface SdownfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdownfile
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int deleteByPrimaryKey(SdownfileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdownfile
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insert(Sdownfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdownfile
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insertSelective(Sdownfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdownfile
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    Sdownfile selectByPrimaryKey(SdownfileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdownfile
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKeySelective(Sdownfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdownfile
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKey(Sdownfile record);
}