package guide.dao;

import java.util.List;

import guide.bean.Manager;
import guide.bean.Thesis;

public interface ThesisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int deleteByPrimaryKey(String tesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insert(Thesis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insertSelective(Thesis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    Thesis selectByPrimaryKey(String tesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKeySelective(Thesis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table thesis
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKey(Thesis record);

    List<Thesis> getThesis(String teac_id);

    List<Thesis> getthesis(String stuId);

    int  findMax();


}