package guide.dao;

import java.util.List;

import guide.bean.File;

public interface FileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int deleteByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insertSelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    File selectByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKeySelective(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_id
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKey(File record);

	List<File> getFile();
}