package guide.dao;

import guide.bean.Manager;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int deleteByPrimaryKey(String matId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insertSelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    Manager selectByPrimaryKey(String matId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKeySelective(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKey(Manager record);
}