package guide.dao;

import java.util.List;

import guide.bean.Question;
import guide.bean.QuestionKey;

public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int deleteByPrimaryKey(QuestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    Question selectByPrimaryKey(QuestionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKey(Question record);
     
    int countQuestions(String date);
    
    int countQuestion();
    
    int getTeaQuestion(String tea_id);
    
    int getTeaQuestionNull(String tea_id);
    
    public List<Question> findQuesiotnA(String stu_id);
    
    public List<Question> findQuesiotnNA(String stu_id);

	List<Question> getAllNA(String teac_id);

	List<Question> getAll(String teac_id);
    
}