package guide.dao;

import guide.bean.Smessage;
import guide.bean.SmessageKey;

public interface SmessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 学生消息表
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int deleteByPrimaryKey(SmessageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 学生消息表
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insert(Smessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 学生消息表
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insertSelective(Smessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 学生消息表
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    Smessage selectByPrimaryKey(SmessageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 学生消息表
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKeySelective(Smessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table 学生消息表
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKey(Smessage record);
}