package guide.dao;

import guide.bean.Tdownfile;
import guide.bean.TdownfileKey;

public interface TdownfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdownfile
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int deleteByPrimaryKey(TdownfileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdownfile
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insert(Tdownfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdownfile
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int insertSelective(Tdownfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdownfile
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    Tdownfile selectByPrimaryKey(TdownfileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdownfile
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKeySelective(Tdownfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tdownfile
     *
     * @mbg.generated Fri Nov 16 21:37:24 CST 2018
     */
    int updateByPrimaryKey(Tdownfile record);
}